openapi: 3.1.0
info:
  title: Wanderlust Travel API
  version: 1.0.0
  description: RESTful API for hotel management & booking
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Hotel:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        star:
          type: integer
        city:
          type: string
        country:
          type: string
        address:
          type: string
security:
  - bearerAuth: []
paths:
  /hotels:
    get:
      tags:
        - Hotel
      summary: Get all hotels
      parameters:
        - in: query
          name: city
          schema:
            type: string
        - in: query
          name: star
          schema:
            type: integer
      responses:
        "200":
          description: List of hotels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Hotel"
tags: []
